apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpLocust, TaskSet
    import random
    def index(l):
        if random.normalvariate(0,1) > 0.2:
            l.client.get("/")

    def bad(l):
        l.client.get("/bad")

    def query(l):
        l.client.get("/query")

    class UserBehavior(TaskSet):
        tasks = {index: 1, query: 1, bad:2}

    class WebsiteUser(HttpLocust):
        task_set = UserBehavior
        min_wait = 5000
        max_wait = 9000